### ISSUE TITLE
Latest release upload error

### ISSUE THREAD

**Issue by germa89** [pyansys/pymapdl-reader#206]
Latest reader release showed an error:

https://github.com/pyansys/pymapdl-reader/actions/runs/4018598863/jobs/6904846821#step:6:51

I am not sure, but I believe it is because we are uploading the same file many times. 

The directory structure is:

```text
./ansys-mapdl-reader-Linux-3.9:
ansys_mapdl_reader-0.[52](https://github.com/pyansys/pymapdl-reader/actions/runs/4018598863/jobs/6904846821#step:4:53).8-cp39-cp39-manylinux_2_17_x86_[64](https://github.com/pyansys/pymapdl-reader/actions/runs/4018598863/jobs/6904846821#step:4:65).manylinux2014_x86_64.whl

./ansys-mapdl-reader-Windows-3.10:
ansys-mapdl-reader-0.52.8.tar.gz
ansys_mapdl_reader-0.52.8-cp310-cp310-win_amd64.whl

./ansys-mapdl-reader-Windows-3.11:
ansys-mapdl-reader-0.52.8.tar.gz
ansys_mapdl_reader-0.52.8-cp311-cp311-win_amd64.whl

./ansys-mapdl-reader-Windows-3.7:
ansys-mapdl-reader-0.52.8.tar.gz
ansys_mapdl_reader-0.52.8-cp37-cp37m-win_amd64.whl

./ansys-mapdl-reader-Windows-3.8:
ansys-mapdl-reader-0.52.8.tar.gz
ansys_mapdl_reader-0.52.8-cp38-cp38-win_amd64.whl

./ansys-mapdl-reader-Windows-3.9:
ansys-mapdl-reader-0.52.8.tar.gz
ansys_mapdl_reader-0.52.8-cp39-cp39-win_amd64.whl
```

As we can see there is tar.gz file per windows built.

Two options are possible:
* Option 1: Using only one tar.gz file, we need to filter using something like:
```yml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./*3.11/*.tag.gz
            ./**/*.whl
            ./**/*.zip
            ./**/*.pdf
```
* Option 2: Remove the tag.gz file. Since all the releases have one already. However, this one is lighter (no ``.github``, ``.ci``, ... directories).
```yml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./**/*.whl
            ./**/*.zip
            ./**/*.pdf
```
